name: ci.yml

on: [ push, pull_request ]
jobs:
  linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Test x86
        run: cd build && ./test

  linux-qemu-riscv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-riscv64-linux-gnu g++-riscv64-linux-gnu binutils-riscv64-linux-gnu qemu-system-riscv64 qemu-user qemu-user-static

      - name: Configure
        run: cmake -B build -DCMAKE_C_COMPILER=riscv64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=riscv64-linux-gnu-g++

      - name: Build
        run: cmake --build build

      - name: Test RiscV
        run: cd build && qemu-riscv64 -L /usr/riscv64-linux-gnu ./test

  linux-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Test AArch64
        run: cd build && ./test

  windows-x86:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true

      - name: Dependencies
        shell: msys2 {0}
        run: pacman -S git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-python --noconfirm

      - name: Configure
        shell: msys2 {0}
        run: cmake -B build -G Ninja -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

      - name: Build
        shell: msys2 {0}
        run: cmake --build build

      - name: Test
        shell: msys2 {0}
        run: cd build && ./test.exe